/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../../packages/todo-universal/routes/__root'
import { Route as IndexRouteImport } from './../../../packages/todo-universal/routes/index'
import { Route as TodoStatsRouteRouteImport } from './../../../packages/todo-universal/routes/todo/stats/route'
import { Route as TodoIdRouteRouteImport } from './../../../packages/todo-universal/routes/todo/$id/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoStatsRouteRoute = TodoStatsRouteRouteImport.update({
  id: '/todo/stats',
  path: '/todo/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoIdRouteRoute = TodoIdRouteRouteImport.update({
  id: '/todo/$id',
  path: '/todo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todo/$id': typeof TodoIdRouteRoute
  '/todo/stats': typeof TodoStatsRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todo/$id': typeof TodoIdRouteRoute
  '/todo/stats': typeof TodoStatsRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/todo/$id': typeof TodoIdRouteRoute
  '/todo/stats': typeof TodoStatsRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todo/$id' | '/todo/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todo/$id' | '/todo/stats'
  id: '__root__' | '/' | '/todo/$id' | '/todo/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodoIdRouteRoute: typeof TodoIdRouteRoute
  TodoStatsRouteRoute: typeof TodoStatsRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/stats': {
      id: '/todo/stats'
      path: '/todo/stats'
      fullPath: '/todo/stats'
      preLoaderRoute: typeof TodoStatsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/$id': {
      id: '/todo/$id'
      path: '/todo/$id'
      fullPath: '/todo/$id'
      preLoaderRoute: typeof TodoIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodoIdRouteRoute: TodoIdRouteRoute,
  TodoStatsRouteRoute: TodoStatsRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
